markdown: kramdown
lsi: false
safe: true
source: /bax2004rj/bax2004rj.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: cayman